using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyTitleAttribute("RunJS")]
[assembly: AssemblyDescriptionAttribute("The javascript runner")]
[assembly: AssemblyConfigurationAttribute("dev")]
[assembly: AssemblyCompanyAttribute("")]
[assembly: AssemblyProductAttribute("RunJS")]
[assembly: AssemblyCopyrightAttribute("Copyright (C) 2011-2011 Alxandr Productions")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyCultureAttribute("")]
[assembly: AssemblyVersionAttribute("0.3.4290.0")]
[assembly: AssemblyInformationalVersionAttribute("0.3")]

